import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import { Roboto } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const roboto = Roboto({
  weight: "400",
  subsets: ["vietnamese"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Smartshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <AntdRegistry>
        <body>
          <div className="max-w-[1280px] mx-auto relative">
            <Header />
            <main className="text-[#444444] max-w-[1200px] mx-auto w-full px-2 mt-[132px] pt-5">
              {children}
            </main>
          </div>
        </body>
      </AntdRegistry>
    </html>
  );
}
