server:
  port: ${APP_PORT}
spring:
  application:
    name: Ecommerce
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

  # send-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${vheqasktursdcmpv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # file
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: ${API_PREFIX}

# swagger-ui
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# jwt
jwt:
  expiration: ${JWT_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}
  secretKey: ${JWT_SECRET_KEY}

# payment
payment:
  vnPay:
    url: ${PAYMENT_URL}
    tmnCode: ${PAYMENT_TMN_CODE}
    secretKey: ${PAYMENT_SECRET_KEY}
    returnUrl: ${PAYMENT_RETURN_URL}
    version: 2.1.0
    command: pay
    orderType: other

# cloudinary
cloudinary:
  cloudName: ${CLOUDINARY_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}