server:
  port: 8080
spring:
  application:
    name: Ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/Ecommerce
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

# send-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: daocongdanh47@gmail.com
    password: vheqasktursdcmpv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


api:
  prefix: /api/v1

# swagger-ui
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# jwt
jwt:
  expiration: 3600000 # (1 * 60 * 1000 mls) 1 phút 60000
  refreshExpiration: 7200000 # 5 phút 300000
  secretKey: XeKCntPJuk/iJoaxpv9ifO4aj+6TXWpL123R9b47aqH0=

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: TSFZ2A2L
    secretKey: SNIHOORBOFJ6USCIPO48W9H6NYPBAKI4
    returnUrl: http://localhost:8080/api/v1/payments/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other