server:
  port: 8080
spring:
  application:
    name: Ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/Ecommerce
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

# send-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: daocongdanh47@gmail.com
    password: vheqasktursdcmpv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


api:
  prefix: /api/v1

# swagger-ui
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
# jwt
jwt:
  expiration: 60000 # (1 * 60 * 1000 mls) 1 phút 60000
  refreshExpiration: 90000 # 5 phút 300000
  secretKey: XeKCntPJuk/iJoaxpv9ifO4aj+6TXWpL123R9b47aqH0=